"""DEMOCRAC.IA / PEIRS — Catálogo de países monitoreados"""

COUNTRY_CATALOG = {
    "VEN": {"name": "Venezuela",       "flag": "🇻🇪", "election_date": "2025-12-07"},
    "NIC": {"name": "Nicaragua",       "flag": "🇳🇮", "election_date": "2026-11-07"},
    "GTM": {"name": "Guatemala",       "flag": "🇬🇹", "election_date": "2027-06-20"},
    "URY": {"name": "Uruguay",         "flag": "🇺🇾", "election_date": "2029-10-26"},
    "COL": {"name": "Colombia",        "flag": "🇨🇴", "election_date": "2026-03-08"},
    "BRA": {"name": "Brasil",          "flag": "🇧🇷", "election_date": "2026-10-04"},
    "MEX": {"name": "Mexico",          "flag": "🇲🇽", "election_date": "2027-06-06"},
    "ARG": {"name": "Argentina",       "flag": "🇦🇷", "election_date": "2027-10-24"},
    "CHL": {"name": "Chile",           "flag": "🇨🇱", "election_date": "2025-11-23"},
    "BOL": {"name": "Bolivia",         "flag": "🇧🇴", "election_date": "2026-03-22", "last_election": "2025-08-17", "observation_protocol": True, "phase": "electoral"},
    "ECU": {"name": "Ecuador",         "flag": "🇪🇨", "election_date": "2025-02-09"},
    "PER": {"name": "Peru",            "flag": "🇵🇪", "election_date": "2026-04-12"},
    "HND": {"name": "Honduras",        "flag": "🇭🇳", "election_date": "2025-11-30"},
    "SLV": {"name": "El Salvador",     "flag": "🇸🇻", "election_date": "2027-02-28"},
    "PAN": {"name": "Panama",          "flag": "🇵🇦", "election_date": "2029-05-06"},
    "CRI": {"name": "Costa Rica",      "flag": "🇨🇷", "election_date": "2026-02-01"},
    "DOM": {"name": "Rep. Dominicana", "flag": "🇩🇴", "election_date": "2028-05-21"},
    "PRY": {"name": "Paraguay",        "flag": "🇵🇾", "election_date": "2028-04-30"},
    "CUB": {"name": "Cuba",            "flag": "🇨🇺", "election_date": "2028-03-01"},
    "DEU": {"name": "Alemania",        "flag": "🇩🇪", "election_date": "2025-02-23"},
    "FRA": {"name": "Francia",         "flag": "🇫🇷", "election_date": "2027-04-23"},
    "HUN": {"name": "Hungria",         "flag": "🇭🇺", "election_date": "2026-04-12"},
    "POL": {"name": "Polonia",         "flag": "🇵🇱", "election_date": "2027-10-15"},
    "TUR": {"name": "Turquia",         "flag": "🇹🇷", "election_date": "2028-06-18"},
    "RUS": {"name": "Rusia",           "flag": "🇷🇺", "election_date": "2030-03-15"},
    "BLR": {"name": "Bielorrusia",     "flag": "🇧🇾", "election_date": "2025-01-26"},
    "UKR": {"name": "Ucrania",         "flag": "🇺🇦", "election_date": "2025-03-31"},
    "GEO": {"name": "Georgia",         "flag": "🇬🇪", "election_date": "2028-10-26"},
    "ZAF": {"name": "Sudafrica",       "flag": "🇿🇦", "election_date": "2029-05-29"},
    "NGA": {"name": "Nigeria",         "flag": "🇳🇬", "election_date": "2027-02-20"},
    "KEN": {"name": "Kenia",           "flag": "🇰🇪", "election_date": "2027-08-09"},
    "ZWE": {"name": "Zimbabue",        "flag": "🇿🇼", "election_date": "2028-07-30"},
    "GHA": {"name": "Ghana",           "flag": "🇬🇭", "election_date": "2028-12-07"},
    "IND": {"name": "India",           "flag": "🇮🇳", "election_date": "2029-05-01"},
    "PHL": {"name": "Filipinas",       "flag": "🇵🇭", "election_date": "2028-05-13"},
    "IDN": {"name": "Indonesia",       "flag": "🇮🇩", "election_date": "2029-02-14"},
    "THA": {"name": "Tailandia",       "flag": "🇹🇭", "election_date": "2027-05-01"},
    "TUN": {"name": "Tunez",           "flag": "🇹🇳", "election_date": "2029-10-06"},
}
